# QR Decomposition for PCA
Another method of matrix decomposition that can be used for least squares is QR decomposition. This allows us to bypass computing the matrix cross product of $\mathbf{X}^T\mathbf{X}$. We decpmpose $\mathbf{X}$ into two matrices Q and R where Q is an orthogonal matrix and R is upper triangular

In [1]:
source('PCA.R')

In [11]:
set.seed(110)
A <- matrix( sample(1:30,16), ncol=4)
A <- A + t(A)

B = matrix(c(1, 6, -1, 2, -1, -2, 6, 1, -5), nrow = 3, ncol = 3)
A = matrix(c(-5, 1,-1 , 1, -1, 3, -1, 3, 8, 3, 5, 7), nrow = 4, ncol = 3)
qr.Q(qr(B))
qr.R(qr(B)) #upper triangular

qr.Q(qr(A))%*%qr.R(qr(A)) #original A
qr.Q(qr(A))%*%t(qr.Q(qr(A))) #identity

[,1]       [,2]       [,3]        
[1,] -0.1622214  0.6882472 7.071068e-01
[2,] -0.9733285 -0.2294157 2.220446e-16
[3,]  0.1622214 -0.6882472 7.071068e-01

[,1]      [,2]      [,3]      
[1,] -6.164414 0.3244428 -2.7577642
[2,]  0.000000 2.9824045  7.3413035
[3,]  0.000000 0.0000000  0.7071068

[,1] [,2] [,3]
[1,] -5   -1   8   
[2,]  1    3   3   
[3,] -1   -1   5   
[4,]  1    3   7

[,1]        [,2]        [,3]        [,4]       
[1,]  0.99551821  0.04593838  0.03137255 -0.03697479
[2,]  0.04593838  0.52913165 -0.32156863  0.37899160
[3,]  0.03137255 -0.32156863  0.78039216  0.25882353
[4,] -0.03697479  0.37899160  0.25882353  0.69495798

## QR Decomposition by Internal Methods in R

In [12]:
B = matrix(c(1, 6, -1, 2, -1, -2, 6, 1, -5), nrow = 3, ncol = 3)
qr.Q(qr(B)) #Q
qr.R(qr(B)) #R - upper triangular

[,1]       [,2]       [,3]        
[1,] -0.1622214  0.6882472 7.071068e-01
[2,] -0.9733285 -0.2294157 2.220446e-16
[3,]  0.1622214 -0.6882472 7.071068e-01

[,1]      [,2]      [,3]      
[1,] -6.164414 0.3244428 -2.7577642
[2,]  0.000000 2.9824045  7.3413035
[3,]  0.000000 0.0000000  0.7071068

## QR Decomposition by Written Code

In [9]:
myQR(B)

$Q
           [,1]       [,2]         [,3]
[1,] -0.1622214  0.6882472 7.071068e-01
[2,] -0.9733285 -0.2294157 1.665335e-16
[3,]  0.1622214 -0.6882472 7.071068e-01

$R
              [,1]          [,2]       [,3]
[1,] -6.164414e+00  3.244428e-01 -2.7577642
[2,]  1.299904e-15  2.982405e+00  7.3413035
[3,]  1.230852e-15 -2.220446e-16  0.7071068

In [ ]:
## QR for Linear Regression


In [2]:
testing_Linear_Regression <- function(){
  ## Define parameters
  n    <- 100
  p    <- 3

  ## Simulate data from our assumed model.
  ## We can assume that the true intercept is 0
  X    <- matrix(rnorm(100 * 3), nrow = 100)
  beta <- matrix(1:3, nrow = 3)
  Y    <- X %*% beta + rnorm(100)

  ## Save R's linear regression coefficients
  R_coef  <- coef(lm(Y ~ X))

  ## Save our linear regression coefficients
  
  my_coef <- myLM(X, Y)

  ## Are these two vectors different?
  sum_square_diff <- sum((R_coef - my_coef)^2)
  if(sum_square_diff <= 0.001){
    return('Both results are identical')
  }else{
    return('There seems to be a problem...')
  }
}

In [3]:
testing_Linear_Regression()

[1] "Both results are identical"

In [ ]:
## Eigen Decomposition with QR

In [10]:
myEigen_QR(B)

$D
[1] -6.155402 -3.162371  4.317774

$V
           [,1]       [,2]       [,3]
[1,]  0.6047889  0.1083230 -0.7889845
[2,] -0.6029533 -0.5849319 -0.5424962
[3,] -0.5202669  0.8038164 -0.2884466