# QR Decomposition for PCA
Another method of matrix decomposition that can be used for least squares is QR decomposition. This allows us to bypass computing the matrix cross product of $\mathbf{X}^T\mathbf{X}$. We decpmpose $\mathbf{X}$ into two matrices Q and R where Q is an orthogonal matrix and R is upper triangular

In [1]:
source('PCA.R')

## QR Decomposition by Internal Methods in R

In [2]:
B = matrix(c(1, 6, -1, 2, -1, -2, 6, 1, -5), nrow = 3, ncol = 3)
qr.Q(qr(B)) #Q
qr.R(qr(B)) #R - upper triangular

[,1]       [,2]       [,3]        
[1,] -0.1622214  0.6882472 7.071068e-01
[2,] -0.9733285 -0.2294157 2.220446e-16
[3,]  0.1622214 -0.6882472 7.071068e-01

[,1]      [,2]      [,3]      
[1,] -6.164414 0.3244428 -2.7577642
[2,]  0.000000 2.9824045  7.3413035
[3,]  0.000000 0.0000000  0.7071068

## QR Decomposition by Written Code

In [3]:
myQR(B)

$Q
           [,1]       [,2]         [,3]
[1,] -0.1622214  0.6882472 7.071068e-01
[2,] -0.9733285 -0.2294157 1.665335e-16
[3,]  0.1622214 -0.6882472 7.071068e-01

$R
              [,1]          [,2]       [,3]
[1,] -6.164414e+00  3.244428e-01 -2.7577642
[2,]  1.299904e-15  2.982405e+00  7.3413035
[3,]  1.230852e-15 -2.220446e-16  0.7071068

## QR for Linear Regression
We perform QR decomposition to the matrix $(\mathbf{X}\mathbf{Y})$.

$$ \begin{bmatrix} \mathbf{X} & \mathbf{Y} \end{bmatrix}
\xrightarrow[]{Q^T}
\begin{bmatrix} R & \mathbf{Y}^* \end{bmatrix}
=
\begin{bmatrix}
    R_1 & \mathbf{Y}_1^*\\
    0 & \mathbf{Y}_2^*\\
\end{bmatrix}$$

Where $R_1$is an upper triangular square matrix.

Solving the least squares problem is equivalent to solving:
$$ \min_{\beta}||\mathbf{Y}^* -R\beta ||^2= \min_{\beta}(||\mathbf{Y}_1^* -R_1\beta ||^2 +|| \mathbf{Y}_2^*||^2)$$

The solution to $\widehat{\beta} = R_1^{-1}\mathbf{Y}_1^*$

In [4]:
# Testing function comparing base R functions for regression
# to the functions created for QR decomposition and regression
# implemented here by hand

testing_Linear_Regression <- function(){
  ## Define parameters
  n    <- 100
  p    <- 3

  ## Simulate data from our assumed model.
  ## We can assume that the true intercept is 0
  X    <- matrix(rnorm(100 * 3), nrow = 100)
  beta <- matrix(1:3, nrow = 3)
  Y    <- X %*% beta + rnorm(100)

  ## Save R's linear regression coefficients
  R_coef  <- coef(lm(Y ~ X))

  ## Save our linear regression coefficients
  
  my_coef <- myLM(X, Y)

  ## Are these two vectors different?
  sum_square_diff <- sum((R_coef - my_coef)^2)
  if(sum_square_diff <= 0.001){
    return('Both results are identical')
  }else{
    return('There seems to be a problem...')
  }
}

In [5]:
testing_Linear_Regression()

[1] "Both results are identical"

## Eigen Decomposition with QR and PCA
Another decomposition is the eigen decomposition. A symmetric matrix $\Sigma$ can be diagonalized as $\Sigma  = Q\Lambda Q^T$ where $Q$ is orthognal and $\Lambda$ is diagonal with the ordered (decending) eigenvalues along the diagonal.

The power method is used here to extract the eigenvalues and eigenvectors

These can then be used for principle component analysis where if we originally had a data matrix $X$ of dimension $n \times p$, we choose a $d <p$ representing the number of principle components (dimensions) we wish to keep in our data. We use the reduced eigenvectors to transform the original data to a new basis

In [6]:
myEigen_QR(B)

$D
[1] -6.155402 -3.162371  4.317774

$V
           [,1]       [,2]       [,3]
[1,]  0.6047889  0.1083230 -0.7889845
[2,] -0.6029533 -0.5849319 -0.5424962
[3,] -0.5202669  0.8038164 -0.2884466